### ISSUE TITLE
How to Build: Debian Jessie

### ISSUE THREAD

**Issue by tflanagan** [wkhtmltopdf/packaging#25]
I've installed 0.12.5 via apt, so I know it's possible.

But I cannot for the life of me get it to compile via source.

Do you have exact steps to build this? I've looked at various issues, but none are helping.

Various attempts:
From #12:
```
****@****:~/packaging$ ./build compile-docker jessie-amd64 ../wkhtmltopdf/ release
flag provided but not defined: -v/home/****/wkhtmltopdf:/src
See 'docker run --help'.
docker run --rm -v/home/****/wkhtmltopdf:/src -v/home/****/packaging/release:/tgt -w/tgt/qt --user 1001:1001 wkhtmltopdf/packaging:0.12_jessie-amd64 /src/qt/configure -opensource -confirm-license -fast -release -static -graphicssystem raster -webkit -exceptions -xmlpatterns -system-zlib -system-libpng -system-libjpeg -no-libmng -no-libtiff -no-accessibility -no-stl -no-qt3support -no-phonon -no-phonon-backend -no-opengl -no-declarative -no-script -no-scripttools -no-sql-ibase -no-sql-mysql -no-sql-odbc -no-sql-psql -no-sql-sqlite -no-sql-sqlite2 -no-mmx -no-3dnow -no-sse -no-sse2 -no-multimedia -nomake demos -nomake docs -nomake examples -nomake tools -nomake tests -nomake translations -silent -xrender -largefile -iconv -openssl-linked -no-javascript-jit -no-rpath -no-dbus -no-nis -no-cups -no-pch -no-gtkstyle -no-nas-sound -no-sm -no-xshape -no-xinerama -no-xcursor -no-xfixes -no-xrandr -no-mitshm -no-xinput -no-xkb -no-glib -no-gstreamer -no-icu -no-openvg -no-xsync -no-audio-backend -no-sse3 -no-ssse3 -no-sse4.1 -no-sse4.2 -no-avx -no-neon  --prefix=/tgt/qt
command failed: exit code 2
```

From #7 
```
****@****:~/packaging$ ./build package-docker ../wkhtmltopdf release
Traceback (most recent call last):
  File "./build", line 297, in <module>
    main()
  File "./build", line 294, in main
    func(yaml.load(f.read()), **args)
  File "./build", line 116, in package_docker
    if config['docker-targets'][target].get('qemu'):
KeyError: '../wkhtmltopdf'
```

Any help would be appreciated.

(Yes, I've properly cloned the wkhtmltopdf and qt repos)

**Comment by ashkulz** [comment]
What's the OS you're running it on and the versions of dependent tools i.e. `python` and `docker`? You should be able to generate a build using `./build package-docker jessie-amd64 ~/wkhtmltopdf` (not sure if an absolute path is required, I always used one).

**Comment by tflanagan** [comment]
@ashkulz 

Running Debian Jessie;

```
$ uname -a
Linux development 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u3 (2017-08-15) x86_64 GNU/Linux
$ python --version
Python 2.7.9
$ docker --version
Docker version 1.6.2, build 7c8fca2
```

I've tried a couple relative and absolute paths, results in the same error:

```
$ ./build package-docker jessie-amd64 ~/wkhtmltopdf
flag provided but not defined: -v/home/****/wkhtmltopdf:/src
See 'docker run --help'.
docker run --rm -v/home/****/wkhtmltopdf:/src -v/home/****/packaging/targets/jessie-amd64:/tgt -w/tgt/qt --user 1001:1001 wkhtmltopdf/packaging:0.12_jessie-amd64 /src/qt/configure -opensource -confirm-license -fast -release -static -graphicssystem raster -webkit -exceptions -xmlpatterns -system-zlib -system-libpng -system-libjpeg -no-libmng -no-libtiff -no-accessibility -no-stl -no-qt3support -no-phonon -no-phonon-backend -no-opengl -no-declarative -no-script -no-scripttools -no-sql-ibase -no-sql-mysql -no-sql-odbc -no-sql-psql -no-sql-sqlite -no-sql-sqlite2 -no-mmx -no-3dnow -no-sse -no-sse2 -no-multimedia -nomake demos -nomake docs -nomake examples -nomake tools -nomake tests -nomake translations -silent -xrender -largefile -iconv -openssl-linked -no-javascript-jit -no-rpath -no-dbus -no-nis -no-cups -no-pch -no-gtkstyle -no-nas-sound -no-sm -no-xshape -no-xinerama -no-xcursor -no-xfixes -no-xrandr -no-mitshm -no-xinput -no-xkb -no-glib -no-gstreamer -no-icu -no-openvg -no-xsync -no-audio-backend -no-sse3 -no-ssse3 -no-sse4.1 -no-sse4.2 -no-avx -no-neon  --prefix=/tgt/qt
command failed: exit code 2
```

```
$ ./build package-docker jessie-amd64 /home/****/wkhtmltopdf
flag provided but not defined: -v/home/****/wkhtmltopdf:/src
See 'docker run --help'.
docker run --rm -v/home/****/wkhtmltopdf:/src -v/home/****/packaging/targets/jessie-amd64:/tgt -w/tgt/qt --user 1001:1001 wkhtmltopdf/packaging:0.12_jessie-amd64 /src/qt/configure -opensource -confirm-license -fast -release -static -graphicssystem raster -webkit -exceptions -xmlpatterns -system-zlib -system-libpng -system-libjpeg -no-libmng -no-libtiff -no-accessibility -no-stl -no-qt3support -no-phonon -no-phonon-backend -no-opengl -no-declarative -no-script -no-scripttools -no-sql-ibase -no-sql-mysql -no-sql-odbc -no-sql-psql -no-sql-sqlite -no-sql-sqlite2 -no-mmx -no-3dnow -no-sse -no-sse2 -no-multimedia -nomake demos -nomake docs -nomake examples -nomake tools -nomake tests -nomake translations -silent -xrender -largefile -iconv -openssl-linked -no-javascript-jit -no-rpath -no-dbus -no-nis -no-cups -no-pch -no-gtkstyle -no-nas-sound -no-sm -no-xshape -no-xinerama -no-xcursor -no-xfixes -no-xrandr -no-mitshm -no-xinput -no-xkb -no-glib -no-gstreamer -no-icu -no-openvg -no-xsync -no-audio-backend -no-sse3 -no-ssse3 -no-sse4.1 -no-sse4.2 -no-avx -no-neon  --prefix=/tgt/qt
command failed: exit code 2
```

```
$ ./build package-docker jessie-amd64 ../wkhtmltopdf
flag provided but not defined: -v/home/****/wkhtmltopdf:/src
See 'docker run --help'.
docker run --rm -v/home/****/wkhtmltopdf:/src -v/home/****/packaging/targets/jessie-amd64:/tgt -w/tgt/qt --user 1001:1001 wkhtmltopdf/packaging:0.12_jessie-amd64 /src/qt/configure -opensource -confirm-license -fast -release -static -graphicssystem raster -webkit -exceptions -xmlpatterns -system-zlib -system-libpng -system-libjpeg -no-libmng -no-libtiff -no-accessibility -no-stl -no-qt3support -no-phonon -no-phonon-backend -no-opengl -no-declarative -no-script -no-scripttools -no-sql-ibase -no-sql-mysql -no-sql-odbc -no-sql-psql -no-sql-sqlite -no-sql-sqlite2 -no-mmx -no-3dnow -no-sse -no-sse2 -no-multimedia -nomake demos -nomake docs -nomake examples -nomake tools -nomake tests -nomake translations -silent -xrender -largefile -iconv -openssl-linked -no-javascript-jit -no-rpath -no-dbus -no-nis -no-cups -no-pch -no-gtkstyle -no-nas-sound -no-sm -no-xshape -no-xinerama -no-xcursor -no-xfixes -no-xrandr -no-mitshm -no-xinput -no-xkb -no-glib -no-gstreamer -no-icu -no-openvg -no-xsync -no-audio-backend -no-sse3 -no-ssse3 -no-sse4.1 -no-sse4.2 -no-avx -no-neon  --prefix=/tgt/qt
command failed: exit code 2

**Comment by ashkulz** [comment]
I think the docker version is too old, can you check with the latest version? It works when running from Ubuntu 18.04.

**Comment by tflanagan** [comment]
@ashkulz Thanks for the quick response - I'll give it a try on a newer machine and report back

**Comment by tflanagan** [comment]
Ah, yes - I am a noob when it comes to docker's ecosystem. Updating docker has resolved this exit code failure.

Thanks again.

**Comment by ashkulz** [comment]
docker 1.6.2 is from 2015, guess a lot has changed...

**Comment by tflanagan** [comment]
Yea the official source lists for Debian are a bit dated for Docker...
