### ISSUE TITLE
Is there any hope of a macOS ARM build?

### ISSUE THREAD

**Issue by emendelson** [wkhtmltopdf/packaging#98]
I use wkhtmltopdf in various projects that run on macOS. As far as I know, there are no binaries for Apple Silicon (M1), and I haven't figured out how to build on an M1 Mac.

Is there any hope of getting an ARM build for the Mac?

Thanks to any help and advice.

**Comment by Snarik** [comment]
I have a similar issue, does not work when I enable rosetta either.

**Comment by ashkulz** [comment]
@Snarik what is the error you get?

**Comment by soaresRibeiro** [comment]
It's working for me. Installed via Homebrew on the terminal in Rosetta mode.
1 - Run the terminal in Rosetta mode.
2 - brew install wkhtmltopdf

**Comment by ashkulz** [comment]
I don't have access to a M1 and I think it'll hard to port Qt4 to it, unless the arm64 support works as-is. So Rosetta seems to be the only option for the foreseeable future.

**Comment by soaresRibeiro** [comment]
I still can't do wkhtmltopdf. It generates the pdf, but without the project's css. If I can't solve it, I think I'll have to use a docker = (

**Comment by Snarik** [comment]
> It's working for me. Installed via Homebrew on the terminal in Rosetta mode.
> 1 - Run the terminal in Rosetta mode.
> 2 - brew install wkhtmltopdf

This was the solution for me. I had to completely remove Brew, start my terminal in rosetta mode, reinstall it, and then build my packages.

**Comment by soaresRibeiro** [comment]
> > It's working for me. Installed via Homebrew on the terminal in Rosetta mode.
> > 1 - Run the terminal in Rosetta mode.
> > 2 - brew install wkhtmltopdf
> 
> This was the solution for me. I had to completely remove Brew, start my terminal in rosetta mode, reinstall it, and then build my packages.

I'll probably have to do that too, since I installed everything natively except wkhtml.

**Comment by Snarik** [comment]
Yeah brew just does screwy things when you try to install it as ARM64. Better to just run your whole dev env as x86, the performance hit is minor I've found. Good luck.

**Comment by jtelcontar** [comment]
Has anyone had any luck installing wkhtmltopdf in a Docker container on an M1 Mac? I just got a new dev machine for work, and one of the steps in our custom Dockerfile is the following:

```
# Install wkhtmltopdf
RUN wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.stretch_amd64.deb \
  && dpkg -i wkhtmltox_0.12.6-1.stretch_amd64.deb \
  && rm wkhtmltox_0.12.6-1.stretch_amd64.deb
```

This fails when I build the container due to the package architecture and system architecture mismatch.
```
#7 10.53 dpkg: error processing archive wkhtmltox_0.12.6-1.stretch_amd64.deb (--install):
#7 10.53  package architecture (amd64) does not match system (arm64)
#7 10.54 Errors were encountered while processing:
#7 10.54  wkhtmltox_0.12.6-1.stretch_amd64.deb
------
failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.stretch_amd64.deb   && dpkg -i wkhtmltox_0.12.6-1.stretch_amd64.deb   && rm wkhtmltox_0.12.6-1.stretch_amd64.deb]: exit code: 1
```

My next step was going to be attempting to run my terminal in Rosetta mode to see if it will build that way.

**Comment by cclauss** [comment]
I believe that this issue can be closed with @jtelcontar solution above:
```
# Install wkhtmltopdf
RUN wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.stretch_arm64.deb \
  && dpkg -i wkhtmltox_0.12.6-1.stretch_arm64.deb \
  && rm wkhtmltox_0.12.6-1.stretch_arm64.deb
```

**Comment by ashkulz** [comment]
@cclauss that solves the docker based workflow, not a native mac package for M1 so I think this issue should still remain open.

**Comment by sscotti** [comment]
I ran into a similar issue mentioned by  jtelcontar.  I have a Docker package that I usually run on an UBUNTU host and also an Intel Mac.  In the DockerFile I have this:

```
COPY wkhtmltox_0.12.6-1.buster_amd64.deb /
RUN dpkg -i /wkhtmltox_0.12.6-1.buster_amd64.deb
```
and that works fine for the Intel Mac and UBUNTU server (a Dell R710 Xeon).

I'd have to look at the error on the M1 because that is a collaborator, but it is an architecture error message.

I tried changing to arm64, and that also gives an error with buster build from [Downloads](https://wkhtmltopdf.org/downloads.html) for the arm architecture.  It might be that I need to make some additional adjustments in my build ?

Previously I also think I got wkhtmltopdf to work via Docker by using apt install wkhtmltopdf with a Debian Docker container and then also adding some additional packages, like xvfb and others.  That was without using the .deb package and it had / has QT support.  I like using the pre-built .deb packages, but using apt install is not a bad option either.

**Comment by cclauss** [comment]
install_wkhtml2x.sh
```bash
#!/bin/bash -x

set -e

# https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox_0.12.5-1.buster_amd64.deb
# https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.buster_arm64.deb

# If running on an M1 Mac...
if [[ "${TARGETARCH}" == "arm64" ]]; then
    WKHTMLTOX_URL="https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1"
    WKHTMLTOX_DEB="wkhtmltox_0.12.6-1.buster_arm64.deb"
else
    WKHTMLTOX_URL="https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5"
    WKHTMLTOX_DEB="wkhtmltox_0.12.5-1.buster_amd64.deb"
fi

wget ${WKHTMLTOX_URL}/${WKHTMLTOX_DEB}
sudo dpkg -i ${WKHTMLTOX_DEB}
rm ${WKHTMLTOX_DEB}
```

**Comment by sscotti** [comment]
Christian, I'll give that a try, thanks.

Might have to clean up my DockerFile.  Below is part of what I had.

I think I am using just one of those PIP modules, and not sure if I need the font-packages if I am using the .deb package.
I don't have the M1 Mac myself, but I might get one soon.  Kind of waiting for the 27" version release.

```
RUN pip3 install pdfkit
RUN pip3 install wkhtmltopdf

...
...

RUN apt-get update

RUN apt-get --assume-yes install xz-utils

# Needed for the .deb pacakge, section below builds the wkhtmltopdf package

RUN apt-get --assume-yes install fontconfig
RUN apt-get --assume-yes install xfonts-75dpi
RUN apt-get --assume-yes install xfonts-100dpi
RUN apt-get --assume-yes install xfonts-scalable
RUN apt-get --assume-yes install xfonts-base

COPY wkhtmltox_0.12.6-1.buster_amd64.deb /
RUN dpkg -i wkhtmltox_0.12.6-1.buster_amd64.deb
...
```

**Comment by cclauss** [comment]
Do `apt-get` first and `pip3` second.

Put all your `apt-get install` together into a single RUN command to allow dependency resolution to work.

Put all your `pip3 install` together into a single RUN command to allow dependency resolution to work.

**Comment by sscotti** [comment]
I'll give that a try.  Thanks.  I take it I could add what you suggested to my docker-entrypoint.sh somehow ?

**DockerFile**
```
FROM ....

RUN apt-get update && apt-get --assume-yes install -y \
xz-utils \

# ? Needed for the .deb pacakge, section below builds the wkhtmltopdf package

fontconfig \
xfonts-75dpi \
xfonts-100dpi \
xfonts-scalable \
xfonts-base \
dcmtk

RUN pip3 install pydicom pynetdicom pdfkit imgkit hl7 wkhtmltopdf mysql-connector-python requests

# Move to entrypoint or separate file
# COPY wkhtmltox_0.12.6-1.buster_amd64.deb /
# RUN dpkg -i wkhtmltox_0.12.6-1.buster_amd64.deb

ARG TARGETARCH  # for later use in docker-entrypoint.sh

COPY docker-entrypoint.sh /
```
**docker-entrypoint.sh**

```
#!/usr/bin/env bash
set -o errexit
logfilecommand='--logfile=/etc/orthanc/logs/'
current_time=$(date "+%Y.%m.%d-%H.%M.%S")
logfile=$logfilecommand$current_time.log
# generate the configuration file
cd /startup
python3 generateConfiguration.py

if [[ $TRACE_DICOM == true ]]; then
	trace=--trace-dicom
fi
if [[ $VERBOSE_ENABLED == true ]]; then
	verbosity=--verbose
fi

jobs=""
if [[ $NO_JOBS == true ]]; then
	jobs=--no-jobs
fi

argv=(Orthanc $trace $verbosity $jobs $logfile "$@")
echo "Startup command: ${argv[*]}" >&2
exec "${argv[@]}"
```

**Comment by ztinpn** [comment]
any progress?

**Comment by ashkulz** [comment]
I think [my statement earlier](https://github.com/wkhtmltopdf/packaging/issues/98#issuecomment-904414634) was pretty clear?

**Comment by ztinpn** [comment]
> I think [my statement earlier](https://github.com/wkhtmltopdf/packaging/issues/98#issuecomment-904414634) was pretty clear?

is QT 6 available to build this project? I see qt6 support mac os m1 in https://www.qt.io/blog/qt-on-apple-silicon

**Comment by ashkulz** [comment]
Please read https://wkhtmltopdf.org/status

**Comment by darwinini** [comment]
> It's working for me. Installed via Homebrew on the terminal in Rosetta mode.

I was able to install homebrew natively without using Rosetta mode. This link provides a good set of instructions which worked for me (m1 max). 

https://www.funkyspacemonkey.com/how-to-install-homebrew-on-m1-macs-running-macos-monterey

**Comment by mark-young-atg** [comment]
I'm not much of a Mac person but I have a 2021 MacBook Pro with M1 silicon. I believe I have found a couple of ways to work around this. There may be a reason why my approaches are bad. If so please enlighten me.

**First approach:**

This is based on my having installed wkhtmltopdf using brew: `brew install --cask wkhtmltopdf`

```
rails console
 > WickedPdf.config.merge!({exe_path: '/usr/local/bin/wkhtmltopdf'})
 > pdf = WickedPdf.new.pdf_from_string('Hello World')
  => %PDF-1.4\n1 0 obj\n<<\n ...
```

This approach needs to be coded into the application. It likely needs a coding decision similar to the alternative approach below.

**Alternative approach:**

Monkey patch the gem file ./gems/wkhtmltopdf-binary-0.12.5.1/bin/wkhtmltopdf changing line 27 from
```
RbConfig::CONFIG['host_cpu'] == 'x86_64' ? 'macos_cocoa' : 'macos_carbon'
```
to
```
(%w(x86_64 arm64).include? RbConfig::CONFIG['host_cpu']) ? 'macos_cocoa' : 'macos_carbon'
```

I presume the correct approach is to raise a PR against the wkhtmltopdf-binary gem which includes a correctly compiled binary and a modification to the code that selects the correct binary. I don't know about building a binary, nor whether using the one provided by brew would be in contravention of any licensing rules. I've also noticed there are quite a few PRs to add binaries that are yet to be merged.

So I offer this workaround. Please let me know if either of them will lead to pdf generation problems. Obviously I realise the monkey patch will be wiped out by the next gem update.

**Comment by mireksawicz** [comment]
If anyone is still struggling with installing `wkhtmltopdf` on Mac M1 I have just managed to install it using brew.
I have 2021 MacbookPro M1 and my Terminal runs natively (not through Rosetta) and I just ran 
`brew install wkhtmltopdf`
and that worked for me with no issues

**Comment by thomaspalmer** [comment]
> 

Can confirm this works with PHP on a MacBook from 2022 running an apple silicon chip.

**Comment by gottfrois** [comment]
Running a 2023 Macbook Pro M2 Pro

```sh
$ uname -a
Darwin xxx 22.3.0 Darwin Kernel Version 22.3.0: Mon Jan 30 20:39:46 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6020 arm64
```

```sh
$ brew install wkhtmltopdf
...
$ /usr/local/bin/wkhtmltopdf
zsh: bad CPU type in executable: /usr/local/bin/wkhtmltopdf
```

**Comment by sabinnitu** [comment]
Installing wkhtmltopdf in a Docker container on M1 Mac. The code in the Dockerfile:

```
RUN apt-get update \
    && apt-get install -y xfonts-75dpi wget \
    && apt-get install -y xfonts-base wget \
    && wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6.1-2/wkhtmltox_0.12.6.1-2.jammy_arm64.deb \
    && apt install -y ./wkhtmltox_0.12.6.1-2.jammy_arm64.deb \
    && rm ./wkhtmltox_0.12.6.1-2.jammy_arm64.deb
```

**Comment by forthrin** [comment]
> If anyone is still struggling with installing `wkhtmltopdf` on Mac M1 I have just managed to install it using brew. I have 2021 MacbookPro M1 and my Terminal runs natively (not through Rosetta) and I just ran `brew install wkhtmltopdf` and that worked for me with no issues

How did you manage this?

```
~$ uname -a
Darwin 22.3.0; root:xnu-8792.81.3~2/RELEASE_ARM64_T8103 arm64
$ brew reinstall wkhtmltopdf
==> Downloading https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-2/wkhtmltox-0.12.6-2.macos-cocoa.pkg
wkhtmltopdf was successfully installed!
-bash: /usr/local/bin/wkhtmltoimage: Bad CPU type in executable
-bash: /usr/local/bin/wkhtmltopdf: Bad CPU type in executable
```

**Comment by TimZander** [comment]
I am able to install via brew and run the binaries, but my application still is unable to run the library
```
timzander@Timothys-MacBook-Pro ~ % uname -a
Darwin Timothys-MacBook-Pro.local 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:58 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6020 arm64
timzander@Timothys-MacBook-Pro ~ % brew reinstall wkhtmltopdf
==> Downloading https://github.com/wkhtmltopdf/packaging/releases/download/0.12.
Already downloaded: /Users/timzander/Library/Caches/Homebrew/downloads/bc3fcd9890493f143dbada17d9627acd14efd68dfb72b195a7abca9df3f93361--wkhtmltox-0.12.6-2.macos-cocoa.pkg
==> Uninstalling Cask wkhtmltopdf
==> Running uninstall script /usr/local/bin/uninstall-wkhtmltox
Password:
Forgot package 'org.wkhtmltopdf.wkhtmltox' on '/'.
REMOVE /usr/local/bin/wkhtmltopdf
REMOVE /usr/local/bin/wkhtmltoimage
REMOVE /usr/local/include/wkhtmltox/dllend.inc
REMOVE /usr/local/include/wkhtmltox/dllbegin.inc
REMOVE /usr/local/include/wkhtmltox/image.h
REMOVE /usr/local/include/wkhtmltox/pdf.h
REMOVE /usr/local/lib/libwkhtmltox.0.dylib
REMOVE /usr/local/lib/libwkhtmltox.dylib
REMOVE /usr/local/lib/libwkhtmltox.0.12.6.dylib
REMOVE /usr/local/lib/libwkhtmltox.0.12.dylib
REMOVE /usr/local/share/man/man1/wkhtmltoimage.1.gz
REMOVE /usr/local/share/man/man1/wkhtmltopdf.1.gz
REMOVE /usr/local/include/wkhtmltox
REMOVE /usr/local/bin/uninstall-wkhtmltox
==> Uninstalling packages; your password may be necessary:
==> Removing files:
/usr/local/bin/wkhtmltoimage
/usr/local/bin/wkhtmltopdf
/usr/local/include/wkhtmltox
/usr/local/lib/libwkhtmltox.0.12.dylib
/usr/local/lib/libwkhtmltox.0.dylib
/usr/local/lib/libwkhtmltox.0.12.6.dylib
/usr/local/lib/libwkhtmltox.dylib
==> Purging files for version 0.12.6-2 of Cask wkhtmltopdf
==> Installing Cask wkhtmltopdf
==> Running installer for wkhtmltopdf; your password may be necessary.
Package installers may write to any location; options such as `--appdir` are ignored.
installer: Package name is wkhtmltox-0.12.6-2.macos-cocoa
installer: Installing at base path /
installer: The install was successful.
🍺  wkhtmltopdf was successfully installed!
==> `brew cleanup` has not been run in the last 30 days, running now...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
Removing: /Users/timzander/Library/Caches/Homebrew/openssl@3--3.0.7... (7.5MB)
Removing: /Users/timzander/Library/Caches/Homebrew/Cask/powershell--7.3.2.pkg... (62.3MB)
Removing: /Users/timzander/Library/Logs/Homebrew/openssl@3... (64B)
Removing: /Users/timzander/Library/Logs/Homebrew/ca-certificates... (64B)
Pruned 0 symbolic links and 2 directories from /opt/homebrew
timzander@Timothys-MacBook-Pro ~ % /usr/local/bin/wkhtmltoimage
You need to specify at least one input file, and exactly one output file
Use - for stdin or stdout

Name:
  wkhtmltoimage 0.12.6 (with patched qt)

Synopsis:
  wkhtmltoimage [OPTIONS]... <input file> <output file>
  
Description:
  Converts an HTML page into an image, 

General Options:
      --crop-h <int>                  Set height for cropping
      --crop-w <int>                  Set width for cropping
      --crop-x <int>                  Set x coordinate for cropping
      --crop-y <int>                  Set y coordinate for cropping
  -H, --extended-help                 Display more extensive help, detailing
                                      less common command switches
  -f, --format <format>               Output file format
      --height <int>                  Set screen height (default is calculated
                                      from page content) (default 0)
  -h, --help                          Display help
      --license                       Output license information and exit
      --log-level <level>             Set log level to: none, error, warn or
                                      info (default info)
      --quality <int>                 Output image quality (between 0 and 100)
                                      (default 94)
  -q, --quiet                         Be less verbose, maintained for backwards
                                      compatibility; Same as using --log-level
                                      none
  -V, --version                       Output version information and exit
      --width <int>                   Set screen width, note that this is used
                                      only as a guide line. Use
                                      --disable-smart-width to make it strict.
                                      (default 1024)

Contact:
  If you experience bugs or want to request new features please visit 
  <https://wkhtmltopdf.org/support.html>

timzander@Timothys-MacBook-Pro ~ % /usr/local/bin/wkhtmltopdf
You need to specify at least one input file, and exactly one output file
Use - for stdin or stdout

Name:
  wkhtmltopdf 0.12.6 (with patched qt)

Synopsis:
  wkhtmltopdf [GLOBAL OPTION]... [OBJECT]... <output file>
  
Document objects:
  wkhtmltopdf is able to put several objects into the output file, an object is
  either a single webpage, a cover webpage or a table of contents.  The objects
  are put into the output document in the order they are specified on the
  command line, options can be specified on a per object basis or in the global
  options area. Options from the Global Options section can only be placed in
  the global options area.

  A page objects puts the content of a single webpage into the output document.

  (page)? <input url/file name> [PAGE OPTION]...
  Options for the page object can be placed in the global options and the page
  options areas. The applicable options can be found in the Page Options and 
  Headers And Footer Options sections.

  A cover objects puts the content of a single webpage into the output document,
  the page does not appear in the table of contents, and does not have headers
  and footers.

  cover <input url/file name> [PAGE OPTION]...
  All options that can be specified for a page object can also be specified for
  a cover.

  A table of contents object inserts a table of contents into the output
  document.

  toc [TOC OPTION]...
  All options that can be specified for a page object can also be specified for
  a toc, further more the options from the TOC Options section can also be
  applied. The table of contents is generated via XSLT which means that it can
  be styled to look however you want it to look. To get an idea of how to do
  this you can dump the default xslt document by supplying the
  --dump-default-toc-xsl, and the outline it works on by supplying
  --dump-outline, see the Outline Options section.

Description:
  Converts one or more HTML pages into a PDF document, using wkhtmltopdf patched
  qt.

Global Options:
      --collate                       Collate when printing multiple copies
                                      (default)
      --no-collate                    Do not collate when printing multiple
                                      copies
      --copies <number>               Number of copies to print into the pdf
                                      file (default 1)
  -H, --extended-help                 Display more extensive help, detailing
                                      less common command switches
  -g, --grayscale                     PDF will be generated in grayscale
  -h, --help                          Display help
      --license                       Output license information and exit
      --log-level <level>             Set log level to: none, error, warn or
                                      info (default info)
  -l, --lowquality                    Generates lower quality pdf/ps. Useful to
                                      shrink the result document space
  -O, --orientation <orientation>     Set orientation to Landscape or Portrait
                                      (default Portrait)
  -s, --page-size <Size>              Set paper size to: A4, Letter, etc.
                                      (default A4)
  -q, --quiet                         Be less verbose, maintained for backwards
                                      compatibility; Same as using --log-level
                                      none
      --read-args-from-stdin          Read command line arguments from stdin
      --title <text>                  The title of the generated pdf file (The
                                      title of the first document is used if not
                                      specified)
  -V, --version                       Output version information and exit

Page Options:
      --print-media-type              Use print media-type instead of screen
      --no-print-media-type           Do not use print media-type instead of
                                      screen (default)

Contact:
  If you experience bugs or want to request new features please visit 
  <https://wkhtmltopdf.org/support.html>

timzander@Timothys-MacBook-Pro ~ % 
```
```
Unable to load native library. The platform may be missing native dependencies (libjpeg62, etc). Or the current platform is not supported.

   at WkHtmlToPdfDotNet.ModuleFactory.GetModule()
   at WkHtmlToPdfDotNet.PdfTools.Load()
   at WkHtmlToPdfDotNet.BasicConverter.Convert(IDocument document)
   at WkHtmlToPdfDotNet.SynchronizedConverter.<>n__0(IDocument document)
   at WkHtmlToPdfDotNet.SynchronizedConverter.<>c__DisplayClass4_0.<Convert>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
```

After installing with brew I uninstalled the nuget package and reinstalled it. Still getting the exception

I am also experiencing this issue running the application in parallels(windows vm) on my M2 mac

Any suggestions?

**Comment by TimZander** [comment]
> > If anyone is still struggling with installing `wkhtmltopdf` on Mac M1 I have just managed to install it using brew. I have 2021 MacbookPro M1 and my Terminal runs natively (not through Rosetta) and I just ran `brew install wkhtmltopdf` and that worked for me with no issues
> 
> How did you manage this?
> 
> ```
> ~$ uname -a
> Darwin 22.3.0; root:xnu-8792.81.3~2/RELEASE_ARM64_T8103 arm64
> $ brew reinstall wkhtmltopdf
> ==> Downloading https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-2/wkhtmltox-0.12.6-2.macos-cocoa.pkg
> wkhtmltopdf was successfully installed!
> -bash: /usr/local/bin/wkhtmltoimage: Bad CPU type in executable
> -bash: /usr/local/bin/wkhtmltopdf: Bad CPU type in executable
> ```

This is working fine for me, however I am hoping to generate the libwkhtmltox.dylib file. Is there any documentation on how these are generated and how I might build on for Mac ARM?

**Comment by ashkulz** [comment]
@TimZander you need to run it via Rosetta.
